services:
  - type: web
    name: clipsearch-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: clipsearch-db
          property: connectionString

  - type: web
    name: clipsearch-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10001
      - key: NEXT_PUBLIC_API_URL
        value: https://clipsearch-backend.onrender.com

databases:
  - name: clipsearch-db
    databaseName: clipsearch
    user: clipsearch_user 